### ISSUE TITLE
단일 게시글 좋아요리스트 컴포넌트

### ISSUE THREAD

**Issue by jaegwans** [My-Pack/MyPack-Web#64]
## 설명

> 좋아요 리스트 페이지 

### 할 일

- [x] 좋아요 리스트페이지
- [x] 목 api 연결

**Comment by hanseulhee** [comment]
좋아요 리스트 어떻게 보여주실 건가요??

<img width="50%" alt="스크린샷 2023-05-27 오후 3 18 26" src="https://github.com/My-Pack/MyPack-Web/assets/63100352/2dca3bec-7bc9-444d-91fc-f045f23e18db">

이런 식으로 하실 생각이시라면 cardDetail page commentWrapper에 인스타처럼 추가하면 좋을 것 같아요!

**Comment by jaegwans** [comment]
@hanseulhee 엇 저는 본인이 좋아요 누른 카드들 목록 생각한거였는데,, 저것부터 필요해보이네요 일단 위 인스타처럼 단일 게시글 좋아요 리스트 컴포넌트 부터 만들어볼게요!

**Comment by hanseulhee** [comment]
아아 그런거군요 좋아요!!
